version: "3.8"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    # Para persistencia de datos
    # volumes:
    #   - mongodb_data:/data/db
# Si usas el volumen, descomenta esto:
# volumes:
#   mongodb_data:
